### ISSUE TITLE
gRPCとProtobufを更新する

### ISSUE THREAD

**Issue by owhinata** [owhinata/etrobo_tr_ex3#5]
protocが古くpythonから使えない
```
python -m etrobo_ctrl
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/Users/ouwa/work/github/etrobo_ctrl/etrobo_ctrl/__init__.py", line 2, in <module>
    from etrobo_ctrl.etrobo_control_pb2 import *
  File "/Users/ouwa/work/github/etrobo_ctrl/etrobo_ctrl/etrobo_control_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/Users/ouwa/work/github/etrobo_ctrl/.venv/lib/python3.11/site-packages/google/protobuf/descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```

**Comment by owhinata** [comment]
```
sudo apt-get remove libgrpc++-dev libgrpc-dev libprotobuf-dev protobuf-compiler protobuf-compiler-grpc python3-grpc-tools python3-grpcio python3-protobuf libprotobuf-lite23 libprotoc23
```

**Comment by owhinata** [comment]
```
libgrpc++-dev protobuf-compiler-grpc python3-grpcio python3-grpc-tools
```

**Comment by owhinata** [comment]
結局protobufのバージョンを上げると今度はEtRoboアプリがビルドできなくなったので、protobufはapt installで入るものを使う
```
libgrpc++-dev:armhf                  1.30.2-3+rpi1                    armhf        high performance general RPC framework (development)
libgrpc-dev:armhf                    1.30.2-3+rpi1                    armhf        high performance general RPC framework (development)
libprotobuf-dev:armhf                3.12.4-1                         armhf        protocol buffers C++ library (development files) and proto files
protobuf-compiler                    3.12.4-1                         armhf        compiler for protocol buffer definition files
protobuf-compiler-grpc               1.30.2-3+rpi1                    armhf        high performance general RPC framework - protobuf plugin
python3-grpc-tools                   1.14.1-1+b5                      armhf        Protobuf code generator for gRPC (Python 3)
python3-grpcio                       1.30.2-3+rpi1                    armhf        GRPC system (Python 3)
python3-protobuf                     3.12.4-1                         armhf        Python 3 bindings for protocol buffers
```

クライアントは一つ前のコメントに記載した方法で、古いprotobufを入れた。

疎通確認はできたのでクローズする。
